uint8 trajectory_following_mode

uint8 IDLE=0
uint8 AUTONOMY_JOINT = 1
uint8 TELEOPERATION_CARTESIAN = 2
uint8 TELEOPERATION_EEF=3
uint8 TELEOPERATION_JOINT=4
uint8 TELEOPERATION_VR=5
---
bool result
